local basalt = require("basalt")

function Buttons(main)
    local buttons = {}

    buttons.button1 = main:addButton()
        :setText("1")
        :setSize(5, 3)
        :setBackground(colors.gray)
        :setForeground(colors.white)
        :setPosition(2, 8)

    buttons.button2 = main:addButton()
        :setText("2")
        :setSize(5, 3)
        :setBackground(colors.gray)
        :setForeground(colors.white)
        :setPosition(8, 8)

    buttons.button3 = main:addButton()
        :setText("3")
        :setSize(5, 3)
        :setBackground(colors.gray)
        :setForeground(colors.white)
        :setPosition(14, 8)

    buttons.button4 = main:addButton()
        :setText("4")
        :setSize(5, 3)
        :setBackground(colors.gray)
        :setForeground(colors.white)
        :setPosition(2, 12)

    buttons.button5 = main:addButton()
        :setText("5")
        :setSize(5, 3)
        :setBackground(colors.gray)
        :setForeground(colors.white)
        :setPosition(8, 12)

    buttons.button6 = main:addButton()
        :setText("6")
        :setSize(5, 3)
        :setBackground(colors.gray)
        :setForeground(colors.white)
        :setPosition(14, 12)

    buttons.button7 = main:addButton()
        :setText("7")
        :setSize(5, 3)
        :setBackground(colors.gray)
        :setForeground(colors.white)
        :setPosition(2, 16)

    buttons.button8 = main:addButton()
        :setText("8")
        :setSize(5, 3)
        :setBackground(colors.gray)
        :setForeground(colors.white)
        :setPosition(8, 16)

    buttons.button9 = main:addButton()
        :setText("9")
        :setSize(5, 3)
        :setBackground(colors.gray)
        :setForeground(colors.white)
        :setPosition(14, 16)

    buttons.button0 = main:addButton()
        :setText("0")
        :setSize(5, 3)
        :setBackground(colors.lightGray)
        :setForeground(colors.white)
        :setPosition(20, 16)

    buttons.buttonAC = main:addButton()
        :setText("C")
        :setSize(5, 3)
        :setBackground(colors.lightGray)
        :setForeground(colors.white)
        :setPosition(20, 12)

    buttons.buttonEquals = main:addButton()
        :setText("=")
        :setSize(5, 3)
        :setBackground(colors.lightGray)
        :setForeground(colors.white)
        :setPosition(20, 8)

    buttons.buttonPlus = main:addButton()
        :setText("+")
        :setSize(5, 3)
        :setBackground(colors.orange)
        :setForeground(colors.white)
        :setPosition(2, 4)

    buttons.buttonMinus = main:addButton()
        :setText("-")
        :setSize(5, 3)
        :setBackground(colors.orange)
        :setForeground(colors.white)
        :setPosition(8, 4)

    buttons.buttonMultiply = main:addButton()
        :setText("*")
        :setSize(5, 3)
        :setBackground(colors.orange)
        :setForeground(colors.white)
        :setPosition(14, 4)

    buttons.buttonDivision = main:addButton()
        :setText("/")
        :setSize(5, 3)
        :setBackground(colors.orange)
        :setForeground(colors.white)
        :setPosition(20, 4)
    
    return buttons
end

return Buttons